[package]
name = "embed-lib"
version = "0.1.0"
edition = "2021"

[dependencies]
libc = "0.2.112"

[lib]
name = "embed"
crate-type = [
    "dylib",        # .dll, .so, .dynlib
    "staticlib"     # .lib, .a
]
